"""Compile a repository into a structured llms.txt document."""

from __future__ import annotations

import mimetypes
from datetime import datetime, timezone
from pathlib import Path

import pathspec

from .config import Config
from .ignore import load_ignore_spec

# Extensions we always treat as text
TEXT_EXTENSIONS = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".md", ".mdx", ".txt", ".rst", ".adoc",
    ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
    ".html", ".htm", ".css", ".scss", ".less", ".svg",
    ".sh", ".bash", ".zsh", ".fish", ".ps1", ".psm1", ".bat", ".cmd",
    ".cs", ".fs", ".fsx", ".csproj", ".fsproj", ".sln",
    ".java", ".kt", ".kts", ".gradle", ".groovy",
    ".go", ".rs", ".c", ".h", ".cpp", ".hpp",
    ".rb", ".lua", ".R", ".jl", ".swift", ".dart",
    ".sql", ".graphql", ".gql", ".proto",
    ".dockerfile", ".dockerignore", ".editorconfig",
    ".env.example", ".gitattributes",
    ".xml", ".xsl", ".xslt",
}

# Filenames (no extension) we treat as text
TEXT_FILENAMES = {
    "Makefile", "Dockerfile", "Procfile", "Rakefile", "Gemfile",
    "Justfile", "Taskfile", "Vagrantfile",
    "LICENSE", "LICENCE", "CHANGELOG", "CHANGES", "AUTHORS", "CONTRIBUTORS",
    "README", "NOTICE", "CODEOWNERS",
    ".gitignore", ".gitattributes", ".dockerignore",
    ".editorconfig", ".prettierrc", ".eslintrc",
    ".llmsignore",
}


def _is_text_file(path: Path) -> bool:
    """Heuristic: is the file likely a text file we should include?"""
    if path.name in TEXT_FILENAMES:
        return True
    if path.suffix.lower() in TEXT_EXTENSIONS:
        return True
    # Fall back to mimetypes
    mime, _ = mimetypes.guess_type(str(path))
    if mime and mime.startswith("text/"):
        return True
    return False


def _build_tree(
    repo_path: Path,
    spec: pathspec.PathSpec,
    config: Config,
) -> list[Path]:
    """Walk the repo and return sorted list of included file paths (relative)."""
    included: list[Path] = []

    for item in sorted(repo_path.rglob("*")):
        if not item.is_file():
            continue

        rel = item.relative_to(repo_path)
        rel_posix = rel.as_posix()

        # Check ignore rules
        if spec.match_file(rel_posix):
            continue

        # Extension filter
        if config.include_extensions:
            if item.suffix.lower() not in config.include_extensions:
                continue

        # Size check
        try:
            if item.stat().st_size > config.max_file_bytes:
                continue
        except OSError:
            continue

        # Text check
        if not _is_text_file(item):
            continue

        included.append(rel)

    return included


def _render_directory_tree(files: list[Path]) -> str:
    """Render a compact directory tree from a list of relative paths."""
    lines: list[str] = []
    seen_dirs: set[str] = set()

    for f in files:
        parts = f.parts
        # Emit directory lines
        for i in range(len(parts) - 1):
            dir_path = "/".join(parts[: i + 1])
            if dir_path not in seen_dirs:
                seen_dirs.add(dir_path)
                indent = "  " * i
                lines.append(f"{indent}{parts[i]}/")
        # Emit file line
        indent = "  " * (len(parts) - 1)
        lines.append(f"{indent}{parts[-1]}")

    return "\n".join(lines)


def compile_llms_txt(config: Config) -> str:
    """Compile the full llms.txt content from a repository."""
    repo = config.repo_path
    if not repo.is_dir():
        raise FileNotFoundError(f"Repository path does not exist: {repo}")

    spec = load_ignore_spec(repo, config.extra_ignore_patterns)
    files = _build_tree(repo, spec, config)

    parts: list[str] = []

    # Header
    project_name = repo.name
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts.append(f"# {project_name}")
    parts.append("")
    if config.project_description:
        parts.append(config.project_description)
        parts.append("")
    parts.append(f"> Auto-generated by llm-sync-drive on {now}")
    parts.append(f"> Source: {repo}")
    parts.append(f"> Files included: {len(files)}")
    parts.append("")

    # Directory tree
    parts.append("## Directory Structure")
    parts.append("")
    parts.append("```")
    parts.append(_render_directory_tree(files))
    parts.append("```")
    parts.append("")

    # File contents
    parts.append("## File Contents")
    parts.append("")

    for rel in files:
        full = repo / rel
        ext = rel.suffix.lstrip(".")
        lang = ext if ext else ""

        parts.append(f"### {rel.as_posix()}")
        parts.append("")

        try:
            content = full.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            parts.append(f"*Error reading file: {e}*")
            parts.append("")
            continue

        parts.append(f"```{lang}")
        parts.append(content.rstrip())
        parts.append("```")
        parts.append("")

    return "\n".join(parts)
