"""Tests for the repository compiler."""

from pathlib import Path

import pytest

from llm_sync_drive.compiler import (
    _is_text_file,
    _render_directory_tree,
    compile_llms_txt,
)
from llm_sync_drive.config import Config


class TestIsTextFile:
    @pytest.mark.parametrize("name", [
        "main.py", "index.ts", "style.css", "data.json", "config.yaml",
        "page.html", "script.sh", "lib.rs", "app.go", "query.sql",
    ])
    def test_known_extensions(self, name):
        assert _is_text_file(Path(name))

    @pytest.mark.parametrize("name", [
        "Makefile", "Dockerfile", "LICENSE", "README", ".gitignore",
        ".editorconfig", "CHANGELOG", "Procfile",
    ])
    def test_known_filenames(self, name):
        assert _is_text_file(Path(name))

    @pytest.mark.parametrize("name", ["photo.png", "music.mp3", "archive.zip", "video.mp4"])
    def test_binary_files_rejected(self, name):
        assert not _is_text_file(Path(name))


class TestRenderDirectoryTree:
    def test_flat_files(self):
        files = [Path("a.py"), Path("b.py")]
        tree = _render_directory_tree(files)
        assert "a.py" in tree
        assert "b.py" in tree

    def test_nested_dirs(self):
        files = [Path("src/main.py"), Path("src/utils/helpers.py")]
        tree = _render_directory_tree(files)
        assert "src/" in tree
        assert "  main.py" in tree
        assert "  utils/" in tree
        assert "    helpers.py" in tree

    def test_empty(self):
        assert _render_directory_tree([]) == ""

    def test_shared_parent_only_listed_once(self):
        files = [Path("src/a.py"), Path("src/b.py")]
        tree = _render_directory_tree(files)
        assert tree.count("src/") == 1


class TestCompileLlmsTxt:
    @pytest.fixture()
    def mini_repo(self, tmp_path):
        """Create a minimal repo structure for compilation tests."""
        (tmp_path / "hello.py").write_text("print('hello')\n")
        (tmp_path / "README.md").write_text("# My Project\n")
        (tmp_path / "data.bin").write_bytes(b"\x00\x01\x02\x03")
        sub = tmp_path / "src"
        sub.mkdir()
        (sub / "lib.py").write_text("x = 1\n")
        return tmp_path

    def test_compiles_text_files(self, mini_repo):
        cfg = Config(repo_path=mini_repo)
        output = compile_llms_txt(cfg)
        assert "### hello.py" in output
        assert "### README.md" in output
        assert "### src/lib.py" in output
        assert "print('hello')" in output

    def test_excludes_binary_files(self, mini_repo):
        cfg = Config(repo_path=mini_repo)
        output = compile_llms_txt(cfg)
        assert "data.bin" not in output

    def test_header_format(self, mini_repo):
        cfg = Config(repo_path=mini_repo, project_description="Test project")
        output = compile_llms_txt(cfg)
        assert f"# {mini_repo.name}" in output
        assert "Test project" in output
        assert "Auto-generated by llm-sync-drive" in output
        assert "## Directory Structure" in output
        assert "## File Contents" in output

    def test_extension_filter(self, mini_repo):
        cfg = Config(repo_path=mini_repo, include_extensions=[".py"])
        output = compile_llms_txt(cfg)
        assert "### hello.py" in output
        assert "### src/lib.py" in output
        assert "README.md" not in output

    def test_size_filter(self, mini_repo):
        (mini_repo / "big.py").write_text("x" * 200)
        cfg = Config(repo_path=mini_repo, max_file_bytes=100)
        output = compile_llms_txt(cfg)
        assert "big.py" not in output
        assert "hello.py" in output

    def test_nonexistent_repo_raises(self, tmp_path):
        cfg = Config(repo_path=tmp_path / "nonexistent")
        with pytest.raises(FileNotFoundError):
            compile_llms_txt(cfg)

    def test_gitignore_respected(self, mini_repo):
        (mini_repo / ".gitignore").write_text("*.md\n")
        cfg = Config(repo_path=mini_repo)
        output = compile_llms_txt(cfg)
        assert "README.md" not in output
        assert "hello.py" in output

    def test_extra_ignore_patterns(self, mini_repo):
        cfg = Config(repo_path=mini_repo, extra_ignore_patterns=["src/"])
        output = compile_llms_txt(cfg)
        assert "src/lib.py" not in output
        assert "hello.py" in output
