version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      npm-all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automated"
