export enum VoiceErrorCode {
    // Core Errors
    CORE_UNKNOWN = "CORE_UNKNOWN",
    CORE_INVALID_CONFIG = "CORE_INVALID_CONFIG",
    CORE_TIMEOUT = "CORE_TIMEOUT",
    CORE_RESOURCE_EXHAUSTED = "CORE_RESOURCE_EXHAUSTED",

    // Synthesis Errors
    SYNTH_INVALID_VOICE = "SYNTH_INVALID_VOICE",
    SYNTH_INVALID_TEXT = "SYNTH_INVALID_TEXT",
    SYNTH_UNSUPPORTED_LANGUAGE = "SYNTH_UNSUPPORTED_LANGUAGE",
    SYNTH_ENGINE_FAILURE = "SYNTH_ENGINE_FAILURE",

    // DSP Errors
    DSP_INVALID_OPERATION = "DSP_INVALID_OPERATION",
    DSP_PROCESSING_FAILED = "DSP_PROCESSING_FAILED",
    DSP_INVALID_AUDIO_FORMAT = "DSP_INVALID_AUDIO_FORMAT",
    PITCH_SHIFT_FAILED = "PITCH_SHIFT_FAILED",
    UNSUPPORTED_SAMPLE_RATE = "UNSUPPORTED_SAMPLE_RATE",
    AUDIO_FORMAT_UNSUPPORTED = "AUDIO_FORMAT_UNSUPPORTED",

    // IO Errors
    IO_FILE_NOT_FOUND = "IO_FILE_NOT_FOUND",
    IO_READ_ERROR = "IO_READ_ERROR",
    IO_WRITE_ERROR = "IO_WRITE_ERROR",
    IO_NETWORK_ERROR = "IO_NETWORK_ERROR"
}
